version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: cat test.sh
  lint:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run: shellcheck test.sh
workflows:
  version: 2
  all:
    jobs:
      - build
      - lint
