version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: apk add --quiet --no-cache ca-certificates
      - checkout
      - run: mkdir -p ~/report/shellspec
      - run: cp report/results_junit.xml ~/report/shellspec/results_junit.xml
      - store_test_results:
          path: ~/report
      - store_artifacts:
          path: report
#  lint:
#    docker:
#      - image: koalaman/shellcheck-alpine
#    steps:
#      - checkout
#      - run: shellcheck test.sh
