version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: ls
      - store_test_results:
          path: report
#  lint:
#    docker:
#      - image: koalaman/shellcheck-alpine
#    steps:
#      - checkout
#      - run: shellcheck test.sh
