version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: apk add --quiet --no-cache ca-certificates
      - checkout
      - run: ls
      - store_test_results:
          path: report
      - store_artifacts:
          path: report/junit
#  lint:
#    docker:
#      - image: koalaman/shellcheck-alpine
#    steps:
#      - checkout
#      - run: shellcheck test.sh
