version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: apk add --no-progress --no-cache ca-certificates
      - checkout
      - run:
          command: |
            mkdir -p ~/report/shellspec
            cp report/results_junit.xml ~/report/shellspec/
            /bin/false
          when: always
      - store_test_results:
          path: ~/report
      - store_artifacts:
          path: report
#  lint:
#    docker:
#      - image: koalaman/shellcheck-alpine
#    steps:
#      - checkout
#      - run: shellcheck test.sh
