version: 2
jobs:
  build:
    docker:
      - image: wiremind/alpine-curl-ca-certificates
    steps:
      - checkout
      - run: ls
      - store_test_results:
          path: report
      - store_artifacts:
          path: report/shellspec
#  lint:
#    docker:
#      - image: koalaman/shellcheck-alpine
#    steps:
#      - checkout
#      - run: shellcheck test.sh
