version: 2
jobs:
  cat:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: cat test.sh
  lint:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run: shellcheck test.sh
